# Generated by Django 5.2.13 on 2026-04-08 22:31

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oil', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'مورد', 'verbose_name_plural': 'الموردين'},
        ),
        migrations.AlterModelOptions(
            name='suppliertransaction',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'حركة مورد', 'verbose_name_plural': 'حركات الموردين'},
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=255, verbose_name='اسم المورد'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='رصيد أول المدة'),
        ),
        migrations.AlterField(
            model_name='suppliertransaction',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='الرصيد الصافي'),
        ),
        migrations.AlterField(
            model_name='suppliertransaction',
            name='car_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم السيارة'),
        ),
        migrations.AlterField(
            model_name='suppliertransaction',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='لينا'),
        ),
        migrations.AlterField(
            model_name='suppliertransaction',
            name='date',
            field=models.DateField(verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='suppliertransaction',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='علينا'),
        ),
        migrations.AlterField(
            model_name='suppliertransaction',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='بيان'),
        ),
        migrations.AlterField(
            model_name='suppliertransaction',
            name='driver_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم السائق'),
        ),
        migrations.AlterField(
            model_name='suppliertransaction',
            name='oil_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع الزيت'),
        ),
        migrations.AlterField(
            model_name='suppliertransaction',
            name='payment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='تنزيل من الحساب'),
        ),
        migrations.AlterField(
            model_name='suppliertransaction',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='سعر شراء الزيت'),
        ),
        migrations.AlterField(
            model_name='suppliertransaction',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='الحمولة'),
        ),
        migrations.AlterField(
            model_name='suppliertransaction',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='سعر بيع الزيت'),
        ),
        migrations.AlterField(
            model_name='suppliertransaction',
            name='status',
            field=models.CharField(blank=True, max_length=50, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='suppliertransaction',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oil.supplier', verbose_name='المورد'),
        ),
        migrations.AlterField(
            model_name='suppliertransaction',
            name='total_purchase',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='إجمالي الشراء'),
        ),
        migrations.AlterField(
            model_name='suppliertransaction',
            name='total_sale',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='إجمالي البيع'),
        ),
        migrations.AlterField(
            model_name='suppliertransaction',
            name='transaction_type',
            field=models.CharField(choices=[('purchase', 'شراء'), ('sale', 'بيع')], max_length=10, verbose_name='نوع العملية'),
        ),
    ]
