# Generated by Django 5.2.13 on 2026-04-08 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oil', '0002_alter_supplier_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suppliertransaction',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'نموذج مورد', 'verbose_name_plural': 'نماذج الموردين'},
        ),
    ]
