# Generated by Django 5.2.13 on 2026-04-08 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oil', '0003_alter_suppliertransaction_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliertransaction',
            name='oil_type',
            field=models.CharField(blank=True, choices=[('olein_rbd', 'أولين RBD'), ('olein_refined', 'أولين مكرر'), ('stearin', 'استيارين'), ('palm_rbd', 'النخيل RBD'), ('palm_refined', 'النخيل مكرر'), ('kernel_olein', 'نواه أولين'), ('palm_kernel', 'نواه نخيل'), ('sunflower_refined', 'عباد مكرر'), ('soybean_refined', 'صويا مكرر')], max_length=50, null=True, verbose_name='نوع الزيت'),
        ),
    ]
