# Generated by Django 5.2.13 on 2026-04-08 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oil', '0004_alter_suppliertransaction_oil_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='العنوان'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='التليفون'),
        ),
    ]
