# Generated by Django 5.2.13 on 2026-04-08 23:45

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oil', '0006_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('sale', 'بيع')], default='sale', max_length=10, verbose_name='نوع العملية')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='الكمية')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='سعر البيع')),
                ('description', models.TextField(blank=True, null=True, verbose_name='بيان')),
                ('payment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='تحصيل من العميل')),
                ('total_sale', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='إجمالي البيع')),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='علينا (العميل مدين)')),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='سدد (دفع)')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='الرصيد')),
                ('status', models.CharField(blank=True, max_length=50, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oil.customer', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'حركة عميل',
                'verbose_name_plural': 'حركات العملاء',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
