# Generated by Django 5.2.13 on 2026-04-08 23:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oil', '0007_customertransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='StearinReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='الكمية')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='السعر')),
                ('addition', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='إضافة')),
                ('deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='تنزيل')),
                ('driver_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم السائق')),
                ('total_addition', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='إجمالي الإضافة')),
                ('remaining', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='الباقي من التنزيل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'حجز زيت استيارين',
                'verbose_name_plural': 'حجوزات زيت استيارين',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
